site_name: Core Person Vocabulary Documentation
theme:
  name: material
  palette:
    primary: blue
  features:
    - content.code.copy
nav:
  - Home: index.md
  - Classes:
      - Person: Person.md
      - ContactPoint: ContactPoint.md
  - Slots:
      - contactPoint: contactPoint.md
      - birthName: birthName.md
      - birthDate: birthDate.md
      - deathDate: deathDate.md
      - familyName: familyName.md
      - fullName: fullName.md
      - givenName: givenName.md
      - hasEmail: hasEmail.md
      - hasTelephone: hasTelephone.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - attr_list
plugins:
  - search
  - mermaid2